version: '3'
services:
  website:
    image: flashspys/nginx-static
    container_name: website
    networks:
      - traefik
    ports:
      - 8080:80
    volumes:
      - ./build:/static

networks:
  traefik:
    name: traefik
    external: true
